### ISSUE TITLE
Provide a way to ask the waiting Service Worker to skip waiting from the outside

### ISSUE THREAD

**Issue by dfabulich** [w3c/ServiceWorker#1223] opened 2017-11-13 09:13 UTC
It's a common practice to ask users to click an "refresh" or "update" button when a new Service Worker is waiting. The normal way to actually kick off the update is to post a message to the Service Worker, arranging a convention under which the SW can call `skipWaiting()` in the Service Worker's own scope.

It would be convenient if the ServiceWorker object returned by ServiceWorkerRegistration.waiting had a `skipWaiting()` method, so developers wouldn't have to configure a message listener at all. Combined with #1222, you could write code like this:

```js
navigator.serviceWorker.addEventListener('controllerchange', () => window.location.reload());
navigator.serviceWorker.waiting().then(reg => {
  if (confirm('refresh now?')) reg.waiting.skipWaiting();
});
```

(Uh, don't actually use `confirm()` in production; it's just convenient for this example.)

**Comment by mkruisselbrink** [comment] 2017-11-13 18:00
Sounds like a duplicate of #1016?

**Closed by mkruisselbrink** 2017-11-13 18:00 UTC
