### ISSUE TITLE
Spec of Service Worker state

### ISSUE THREAD

**Issue by CYBAI** [w3c/ServiceWorker#1256] opened 2018-01-01 13:26 UTC
In the [`2.1. Service Worker`](https://w3c.github.io/ServiceWorker/#service-worker-concept) section, the spec said 

> A service worker has an associated _**state**_, which is one of _parsed_, _installing_, _installed_, _activating_, _activated_, and _redundant_. It is initially _**parsed**_.

However, in its interface specification which is [`3.1. ServiceWorker`](https://w3c.github.io/ServiceWorker/#serviceworker-interface) section, it said

```rust
enum ServiceWorkerState {
  "installing",
  "installed",
  "activating",
  "activated",
  "redundant"
};
```

> A **ServiceWorker** object has an associated **ServiceWorkerState** object which is itself associated with **service worker's state**.

If the **ServiceWorkerState** is associated to **service worker's state**, I think maybe one of them is incorrect?
Maybe the **parsed** is redundant now?

**Comment by jungkees** [comment] 2018-01-02 02:52
Thanks for filing this. This is indeed a dupe of https://github.com/w3c/ServiceWorker/issues/1162. We'll track it there.

FYI, currently, _parsed_ is a state that isn't exposed to script, but we see some possibility to expose this initial state as https://github.com/w3c/ServiceWorker/issues/1162 and https://github.com/w3c/ServiceWorker/issues/1077 suggest.

**Closed by jungkees** 2018-01-02 02:52 UTC

**Comment by CYBAI** [comment] 2018-01-02 02:59
@jungkees Thanks for the information! I'll keep an eye on the issue.
