### ISSUE TITLE
Worker Update leaves open notifications behind (unclickable)

### ISSUE THREAD

**Issue by gbhrdt** [w3c/ServiceWorker#1337] opened 2018-08-06 13:04 UTC
We open clickable notifications trough our ServiceWorker. When the browser then updates a ServiceWorker (cache expired, or forces trough `ServiceWorkerRegistration.update`), the remaining open notifications become *unclickable*.
I am not sure if should be is the desired behaviour or if I am missing something here.

**Comment by wanderview** [comment] 2018-08-06 15:06
This sounds like a browser bug.  Can you file bugs on the appropriate browser(s) issue tracker?  I'm sure a reproducible test case using glitch.com or something would help get it looked at quicker.  Thanks.

**Comment by wanderview** [comment] 2018-08-08 16:30
Thanks.  I'm closing this spec issue since it appears to be a browser bug.

**Closed by wanderview** 2018-08-08 16:30 UTC
