### ISSUE TITLE
Move service worker spec into w3c

### ISSUE THREAD

**Issue by jakearchibald** [w3c/ServiceWorker#881] opened 2016-04-12 18:19 UTC

**Comment by jakearchibald** [comment] 2016-04-12 18:20
F2F: Do this sooner rather than later

**Comment by jakearchibald** [comment] 2016-04-12 18:21
F2F: We need to decide if we want the repo to redirect, *or* the pages.

We should ask github if they can help us do both.

**Comment by jakearchibald** [comment] 2016-04-12 18:23
F2F: we don't care too much where the project lives, we care way more about broken links

**Comment by slightlyoff** [comment] 2016-04-12 18:29
Re "doing both", the proximate issue we're facing is that we don't know of any way (today) to redirect both project links and GH Pages URLs to the new location at the same time. It seems possible to do one or the other, but not both. See: https://github.com/blog/1508-repository-redirects-are-here

**Comment by ylafon** [comment] 2016-04-13 11:52
IIRC you need to create a 'slightlyoff.github.io' repo in which you can create a ServiceWorker dir, then the tree to the document you want to redirect, finally a minimal document with some js to redirect fragments.

**Comment by jungkees** [comment] 2016-05-13 08:16
Transferring the repo to `github.com/w3c/` and then replace `/spec/service_worker/index.html` in the gh-pages branch of the original repo with a minimal document having the following script may work? (the same for /spec/service_worker_1/index.html)

```js
<script>
  var element = document.createElement('meta');
  element.setAttribute('http-equiv', 'refresh');
  element.setAttribute('content', '0; url=https://w3c.github.io/ServiceWorker/spec/service_worker/' + location.hash);
  document.getElementsByTagName('head')[0].appendChild(element);
</script>
```

/cc @slightlyoff @jakearchibald @mkruisselbrink

**Comment by mkruisselbrink** [comment] 2016-05-13 16:07
> Transferring the repo to github.com/w3c/ and then replace /spec/service_worker/index.html in the gh-pages branch of the original repo

The problem is that by recreating the original repo you lose redirects for things like issues. But I believe that what @ylafon suggested should work: put that redirect document in a "slightlyoff.github.io" repo as ServiceWorker/spec/service_worker/index.html.

**Comment by ylafon** [comment] 2016-06-10 13:38
Btw, ping me when you plan to do this, as specific right are required for the move.

**Comment by jakearchibald** [comment] 2016-07-27 16:43
Pre F2F notes: Alex says this can be done on Saturday.

**Comment by aliams** [comment] 2016-08-03 21:50
Is this still on track to be moved?

**Comment by jakearchibald** [comment] 2016-08-09 10:18
@slightlyoff what's the status on this?

**Comment by slightlyoff** [comment] 2016-08-22 23:03
Done.

**Closed by slightlyoff** 2016-08-22 23:03 UTC
Labels: decided, spec detail
