### ISSUE TITLE
HTMLLinkElement extension is redundant

### ISSUE THREAD

**Issue by SaschaNaz** [w3c/ServiceWorker#1098] opened 2017-03-30 17:58 UTC
All members on the following extension is already defined in HTML:

```webidl
partial interface HTMLLinkElement {
  [CEReactions] attribute USVString scope;
  [CEReactions] attribute WorkerType workerType;
  [CEReactions] attribute boolean useCache;
};
```

```webidl
[HTMLConstructor]
interface HTMLLinkElement : HTMLElement {
  [CEReactions] attribute USVString href;
  [CEReactions] attribute DOMString? crossOrigin;
  [CEReactions] attribute DOMString rel;
  [CEReactions] attribute RequestDestination as; // (default "")
  [SameObject, PutForwards=value] readonly attribute DOMTokenList relList;
  [CEReactions] attribute DOMString media;
  [CEReactions] attribute DOMString nonce;
  [CEReactions] attribute DOMString integrity;
  [CEReactions] attribute DOMString hreflang;
  [CEReactions] attribute DOMString type;
  [SameObject, PutForwards=value] readonly attribute DOMTokenList sizes;
  [CEReactions] attribute DOMString referrerPolicy;
  [CEReactions] attribute USVString scope;
  [CEReactions] attribute WorkerType workerType;
  [CEReactions] attribute boolean useCache;
};
HTMLLinkElement implements LinkStyle;
```

Is there any reason to keep this extension?

**Comment by mkruisselbrink** [comment] 2017-03-30 18:50
No reason. This should be cleaned up on the service worker side now they are defined in HTML. I just haven't gotten around to doing so yet.

**Comment by mkruisselbrink** [comment] 2017-03-31 22:40
And this actually is a duplicate of #1073

**Closed by mkruisselbrink** 2017-03-31 22:40 UTC
